server:
  port: 8084

spring:
  datasource:
    url: jdbc:h2:file:./bookdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  sql:
    init:
      data-locations: classpath:/sql/sql.sql
      mode: never
  flyway:
    enabled: true
    user: sa
    password: password
    execute-in-transaction: true