server:
  port: 8084

spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:h2:file:./bookdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/templates/static/
    locale: en
    locale-resolver: fixed
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  sql:
    init:
      data-locations: classpath:/sql/sql.sql
      mode: never
  flyway:
    enabled: true
    user: sa
    password: password
    execute-in-transaction: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
#logging:
#  level:
#    root: debug

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
azure:
  storage:
    connectionString: ${AZURE_BLOB_CONNECTION_STRING}
    containerName: ${AZURE_BLOB_CONTAINER_NAME}
    linkExpiration: ${AZURE_BLOB_LINK_EXPIRATION}